 * @Author: shifaqiang(石发强)--[14061115@buaa.edu.cn] 
 * @Date: 2018-10 21:37:49
 * @Last Modified by: shifaqiang 
 * @Last Modified time: 2018-10 21:37:49
 * @Desc: Chapter Five

# chapter 5(栈和队列)

## code 1
原书第318页【page 138】   
栈结构的两周实现方式

In [15]:
# stack 下溢出，即空栈访问
class StackUnderflow(ValueError):
    pass

# stack 的顺序表实现，在表尾实现O(1)的元素插入、访问、删除
class SStack():
    def __init__(self):
        self._elems=[]
        
    def is_empty(self):
        return self._elems == []

    def top(self):
        if self.is_empty():
            raise StackUnderflow("in SStack.top()")
        return self._elems[-1]

    def push(self,elem):
        self._elems.append(elem)
        
    def pop(self):
        if self.is_empty():
            raise StackUnderflow("in SStack.pop()")
        return self._elems.pop()

s1=SStack()

print("the serial of push stack is ",end="")
for i in range(5):
    s1.push(2*i+1)
    print(2*i+1,end=" ")
print()

print("the top of the stack is {}".format(s1.top()))

print("the serial of pop stack is ",end="")
for j in range(5):
    print(s1.pop(),end=" ")
print()

# 此时stack空，会报错
print(s1.pop())

the serial of push stack is 1 3 5 7 9 
the top of the stack is 9
the serial of pop stack is 9 7 5 3 1 


StackUnderflow: in SStack.pop()

In [16]:
# stack 的链接表实现，在链表表头实现O(1)的元素插入、访问、删除
class LNode():
    def __init__(self,elem,next_=None):
        self._elem=elem
        self._next=next_

class LStack():
    def __init__(self):
        self._top=None
    
    def is_empty(slef):
        return self._top is None
    
    def top(self):
        if self.is_empty():
            raise StackUnderflow("In LStack.top()")
        return self._top._elem
    
    def push(self,elem):
        self._top=LNode(elem,self._top)
    
    def pop(self):
        if self.is_empty():
            raise StackUnderflow("in LStack.pop()")
        p=self._top
        self._top=p.next
        return p.elem

In [17]:
s2=SStack()

print("the serial of push stack is ",end="")
for i in range(5):
    s2.push(2*i+1)
    print(2*i+1,end=" ")
print()

print("the top of the stack is {}".format(s2.top()))

print("the serial of pop stack is ",end="")
for j in range(5):
    print(s2.pop(),end=" ")
print()

# 此时stack空，会报错
print(s2.pop())

the serial of push stack is 1 3 5 7 9 
the top of the stack is 9
the serial of pop stack is 9 7 5 3 1 


StackUnderflow: in SStack.pop()

## code 2
原书第141页【page 141】   
栈结构的应用1：括号匹配问题

In [18]:
def check_parens(text):
    """括号匹配检查函数，其中text是被检查的正文串"""
    parens="()[]{}" # 所有的括号字符
    open_parens="([{" # 所有的左括号
    opposite={")":"(","]":"[","}":"{"} # 匹配关系字典
    
    def parentheses(text):
        """括号生成器具，每次调用返回text中的下一个括号及其位置"""
        i,text_len=0,len(text)
        for i in range(text_len):
            if text[i] in parens:
                yield i,text[i]
    # 定义保存括号的栈
    st=SStack()
    for index,pr in parentheses(text):
        if pr in open_parens:
            st.push(pr)
        elif st.pop()!=opposite[pr]:
            print("unmatching is found at {} for {}".format(index,pr))
            return False
    if st.is_empty():
        print("all parenthese are correctly matched.")
        return True
    else:
        print("number of parentheses are not correct.")
        return False

In [19]:
check_parens("(3-5)*(6+77*[33+{95/34}])")

all parenthese are correctly matched.


True

## code 3
原书第145页【page 145】   
栈结构的应用2：表达式的表示、变换和计算  
- 前缀表达式：波兰表达式
- 中缀表达式
- 后缀表达式：逆波兰表达式

In [11]:
# 后缀表达式的求值
class ESStack(SStack):
    def depth(self):
        return len(self._elems)

# 后缀表达式的计算
def suf_exp_evaluator(exp):
    """exp is a list which includes all operators and all operands,like [3,"+",2]"""
    operators="+-*/"
    st=ESStack()
    
    # 开始遍历表达式中的每个项
    for x in exp:
        # x is operand
        if x not in operators:
            st.push(float(x))
            continue
        # x is operator
        if st.depth()<2:
            # 操作数不足两个，报错
            raise SyntaxError("short of operand(s)")
        
        # 从栈顶取得两个操作数
        b=st.pop()
        a=st.pop()
        
        # 判断运算符类型进行计算
        if x=="+":
            c=a+b
        elif x=="-":
            c=a-b
        elif x=="*":
            c=a*b
        elif x=="/":
            c=a/b 
        else:
            break
        # 计算结果压入栈顶
        st.push(c)
    
    if st.depth()==1:
        return st.pop()
    raise SyntaxError("Extra operand(s).")
    
# 字符串表项的分割
def suffix_exp_evaluator(line):
    return suf_exp_evaluator(line.split())

def suffix_exp_calculator():
    while True:
        try:
            line=input("Suffix Expression:")
            # 结束条件
            if line=="end": return
            res=suffix_exp_evaluator(line)
            print(res)
        except Exception as ex:
            print("Error:{},{}".format(type(ex),ex.args))

In [12]:
suffix_exp_calculator()

Suffix Expression:3 5 - 6 17 4 * + * 3 /
-49.333333333333336
Suffix Expression:end


## code 4
原书第147页【page 147】   
中缀表达式到后缀表达式的转换

In [16]:
priority={"(":1,"+":3,"-":3,"*":5,"/":5}
infix_operators="+-*/()"

def tokens(line):
    """
    生成器函数，逐项生成line中的每一个小项，为浮点数或者运算符或者左右圆括号
    """
    i,ilen=0,len(line)
    while i<ilen:
        while line[i].isspace():
            i+=1
        if i>=ilen:
            # 预防数组越界
            break
        if line[i] in infix_operators:
            yield line[i]
            i+=1
            continue
        
        # 遇到运算对象（操作数）
        j=i+1
        while(j<ilen and not line[j].isspace() and line[j] not in infix_operators):
            if (line[j]=='e' or line[j]=='E') and j+1<ilen and line[j+1]=='-':
                j+=1
            j+=1
        yield line[i:j]
        i=j
            
def trans_infix_suffix(line):
    st=SStack()
    exp=[]
    
    for x in tokens(line):
        if x not in infix_operators:
            exp.append(x) # 运算对象（操作数）直接送出
        elif st.is_empty() or x=="(":
            st.push(x) #如果符号栈式空的或者扫描遇到左括号，直接压栈
        elif x==")":
            # 处理右括号分支
            while not st.is_empty() and st.top()!="(":
                exp.append(st.pop())
            if st.is_empty():
                # 没有找到与之匹配的左括号则返回错误
                raise SyntaxError("Missing '(',")
            # 正常完成括号中的运算符弹栈之后，弹出左括号扔掉
            st.pop()
        else:
            #处理扫描到的其他运算符号
            while (not st.is_empty()) and priority[st.top()]>priority[x]:
                exp.append(st.pop())
            st.push(x)
    while not st.is_empty():
        # 将符号栈中的所有符号全部弹出，送入后缀计算表达式
        if st.top()=="(":
            # 如果此时还有左括号，则是不匹配
            raise SyntaxError("Extra '('.")
        exp.append(st.pop())
    
    return exp

def test_trans_infix_suffix(s):
    print(s)
    print(trans_infix_suffix(s))
    print("Value:",suf_exp_evaluator(trans_infix_suffix(s)))

In [17]:
test_trans_infix_suffix("( 3 - 5 ) * ( 6 + 17 * 4 ) / 3")

( 3 - 5 ) * ( 6 + 17 * 4 ) / 3
['3', '5', '-', '6', '17', '4', '*', '+', '3', '/', '*']
Value: -49.333333333333336


In [18]:
(3-5)*(6+17*4)/3

-49.333333333333336

## code 5
原书第159页【page 159】   
队列类的实现  
### 队列的核心设计有：
* 空队列的构造
* 出队（判空操作，防止溢出）
* 入队（判满操作，防止覆盖）
* 队列满/空状态的表示,队头队尾指针（数据不变式的构造与维护）

In [38]:
# 队列空时无法访问异常
class QueueUnderFlow(ValueError):
    pass
class SQueue():
    def __init__(self,init_len=8):
        # 存储区长度
        self._len=init_len
        # 存储区（元素存储）
        self._elems=[0]*self._len
        # 队首元素下标
        self._head=0
        # 元素个数
        self._num=0
    def is_empty(self):
        return self._num==0
    def peek(self):
        if self.is_empty():
            raise QueueUnderFlow
        return self._elems[self._head]
    def dequeue(self):
        if self.is_empty():
            raise QueueUnderFlow
        # 出队操作
        e=self._elems[self._head]
        # 出队一个元素之后队首后移，队列元素数减一，保持数据不变式
        self._head=(self._head+1)%self._len
        self._num-=1
        return 1
    def enqueue(self,elem):
        if self._len==self._num:
            # 队列满时扩大存储区
            self.__extend()
        self._elems[(self._head+self._num)%self._len]=elem
        self._num+=1
    def __extend(self):
        old_len=self._len
        self._len*=2
        new_elems=[0]*self._len
        for i in range(old_len):
            self._elems[i]=self._elems[(self._head+i)%old_len]
        self._elems=new_elems
        self._head=0

## code 6
原书第165页【page 165】   
迷宫求解的递归算
### 递归的思路：
* 每个时刻总有一个当前位置，一开始当前位置是迷宫入口
* 如果当前位置是出口，则问题解决
* 如果当前位置无路可走，搜索失败，回退一步
* 取一个可行的当前位置邻居用相同的方法搜索，如果从哪里可以找到通往出口的路径，那么从当前位置到出口的路径也就找到了
### 具体的算法过程：
* mark当前位置已经到过
* 检查当前位置是否为出口，如果是，则成功结束，如果不是，则继续下一步
* 逐个检查当前位置四个邻居是否可以到达出口
* 如果对四个邻居的检查都没有找到出口，则报告失败

In [41]:
## 辅助数据与函数

#首先是一个12*14的迷宫矩阵
import numpy as np
maze=[[1]*14,
     [1,0,0,0,1,1,0,0,0,1,0,0,0,1],
     [1,0,1,0,0,0,0,1,0,1,0,1,0,1],
     [1,0,1,0,1,1,1,1,0,1,0,1,0,1],
     [1,0,1,0,0,0,0,0,0,1,1,1,0,1],
     [1,0,1,1,1,1,1,1,1,1,0,0,0,1],
     [1,0,1,0,0,0,0,0,0,0,0,1,0,1],
     [1,0,0,0,1,1,1,0,1,0,1,1,0,1],
     [1,0,1,0,1,0,1,0,1,0,1,0,0,1],
     [1,0,1,0,1,0,1,0,1,0,1,1,0,1],
     [1,0,1,0,0,0,1,0,0,1,0,0,0,1],
     [1]*14]
startPoint=(1,1)
endPoint=(10,12)
dirs=[(0,1),(1,0),(0,-1),(-1,0)] # 上下左右四个方向

def mark(maze,pos):
    maze[pos[0],pos[1]]=2 
    # 迷宫矩阵里0表示可以通行，1表示无法通行，2表示已经探索过了
    # pos=(i,j)是一个有序数对，表述迷宫矩阵的下标
def passable(maze,pos):
    return maze[pos[0],pos[1]]==0

In [27]:
def find_path(maze,pos,end):
    # 标记当前位置已经搜索过
    mark(maze,pos)
    if pos==end:
        print(pos, end=" ")
        maze[pos[0],pos[1]]=10
        return True
        # 当前位置是出口，直接输出逐个点并结束程序
    # 否则遍历当前位置的四个方向上的邻居
    for i in range(4):
        nextp=pos[0]+dirs[i][0],pos[1]+dirs[i][1]
        if passable(maze,nextp):
            # 值搜索可以通行的相邻位置
            if find_path(maze,nextp,end):
                print(pos, end=" ")
                maze[pos[0],pos[1]]=10
                # 从pos可达出口，则输出逐个点
                return True
    # 遍历四个邻居之后仍然没有找打出口输出问题无解
    print("No solution...")
    return False

In [28]:
maze_1=np.copy(maze)
find_path(maze_1,startPoint,endPoint)

No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
No solution...
(10, 12) (9, 12) (8, 12) (7, 12) (6, 12) (5, 12) (5, 11) (5, 10) (6, 10) (6, 9) (6, 8) (6, 7) (6, 6) (6, 5) (6, 4) (6, 3) (7, 3) (7, 2) (7, 1) (6, 1) (5, 1) (4, 1) (3, 1) (2, 1) (1, 1) 

True

In [29]:
maze_1

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1, 10,  2,  2,  1,  1,  2,  2,  2,  1,  0,  0,  0,  1],
       [ 1, 10,  1,  2,  2,  2,  2,  1,  2,  1,  0,  1,  0,  1],
       [ 1, 10,  1,  2,  1,  1,  1,  1,  2,  1,  0,  1,  0,  1],
       [ 1, 10,  1,  2,  2,  2,  2,  2,  2,  1,  1,  1,  0,  1],
       [ 1, 10,  1,  1,  1,  1,  1,  1,  1,  1, 10, 10, 10,  1],
       [ 1, 10,  1, 10, 10, 10, 10, 10, 10, 10, 10,  1, 10,  1],
       [ 1, 10, 10, 10,  1,  1,  1,  0,  1,  0,  1,  1, 10,  1],
       [ 1,  0,  1,  2,  1,  2,  1,  0,  1,  0,  1,  0, 10,  1],
       [ 1,  0,  1,  2,  1,  2,  1,  0,  1,  0,  1,  1, 10,  1],
       [ 1,  0,  1,  2,  2,  2,  1,  0,  0,  1,  0,  0, 10,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

## code 8
原书第167页【page 167】   
栈和回溯法求解迷宫问题
### 回溯法的主要流程
* 首先把出发点压入栈中
* 在栈不空的情况下反复做下面的动作（栈空是以失败告终）
    - 弹出一项以前保存的信息作为当前点
    - 检查从这里出发前进的可能性(找到下一个可能的探查点)
    - 如果可以向前：存在下一个可行的位置
        - 把从当前点出发的其它可能入栈
        - 把下一个探查点也入栈

In [44]:
def print_path(st,maze):
    while not st.is_empty():
        pos,nxt=st.pop()
        maze[pos[0]][pos[1]]=10
        print(pos,end=" ")
    print()
    print(maze)
def maze_solver(maze,start,end):
    if start==end:
        print(start)
        return
    st= SStack()
    mark(maze,start)
    # 0,1,2,3表示四个不同的方向，作为dirs的索引体现
    st.push((start,0)) #入口和方向0入栈
    while not st.is_empty():
        # 最外层循环表示走不通是回退，到栈顶最后一个还没有探查的方向
        pos,nxt=st.pop()
        for i in range(nxt,4):
            nextp=(pos[0]+dirs[i][0],pos[1]+dirs[i][1])
            if nextp==end:
                st.push((pos,nxt))
                st.push((end,0))
                print_path(st,maze)
            # 遇到未搜索的新位置
            if passable(maze,nextp):
                # 原位置和下一方向入栈
                st.push((pos,i+1))
                mark(maze,nextp)
                # 新位置入栈
                st.push((nextp,0))
                # 退出内层循环
                break
    print("No solution...")

In [45]:
maze_2=np.copy(maze)
maze_solver(maze_2,startPoint,endPoint)

(10, 12) (9, 12) (8, 12) (7, 12) (6, 12) (5, 12) (5, 11) (5, 10) (6, 10) (6, 9) (6, 8) (6, 7) (6, 6) (6, 5) (6, 4) (6, 3) (7, 3) (7, 2) (7, 1) (6, 1) (5, 1) (4, 1) (3, 1) (2, 1) (1, 1) 
[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1 10  2  2  1  1  2  2  2  1  0  0  0  1]
 [ 1 10  1  2  2  2  2  1  2  1  0  1  0  1]
 [ 1 10  1  2  1  1  1  1  2  1  0  1  0  1]
 [ 1 10  1  2  2  2  2  2  2  1  1  1  0  1]
 [ 1 10  1  1  1  1  1  1  1  1 10 10 10  1]
 [ 1 10  1 10 10 10 10 10 10 10 10  1 10  1]
 [ 1 10 10 10  1  1  1  0  1  0  1  1 10  1]
 [ 1  0  1  2  1  2  1  0  1  0  1  0 10  1]
 [ 1  0  1  2  1  2  1  0  1  0  1  1 10  1]
 [ 1  0  1  2  2  2  1  0  0  1  0  0 10  1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1]]
No solution...


## code 9
原书第169页【page 169】   
基于队列的迷宫求解算法

In [48]:
def maze_solver_queue(maze,start,end):
    if start==end:
        print("Path finds.")
        return True
    qu=SQueue()
    mark(maze,start)
    qu.enqueue(start)
    while not qu.is_empty():
        pos=qu.dequeue()
        print(pos)
        for i in range(4):
            nextp=(pos[0]+dirs[i][0],pos[1]+dirs[i][1])
            if passable(maze,nextp):
                if nextp==end:
                    print("Path find.")
                    return True
                mark(maze,nextp)
                qu.enqueue(nextp)
    print("No solution...")