 * @Author: shifaqiang(石发强)--[14061115@buaa.edu.cn] 
 * @Date: 2018-11-15 09:14:53 
 * @Last Modified by:   shifaqiang 
 * @Last Modified time: 2018-11-15 09:14:53
 * @Desc: Chapter Six

# chapter 6(二叉树和树)

## code 1
原书第184页【page 184】  
用list实现二叉树的一组基本函数

In [1]:
def binTree(data,left=None,right=None):
    return [data,left,right]
def isEmpty(btree):
    return btree is None
def getRoot(btree):
    return btree[0]
def getLeft(btree):
    return btree[1]
def getRight(btree):
    return btree[2]
def setRoot(btree,data):
    btree[0]=data
def setLeft(btree,data):
    btree[1]=data
def setRight(btree,data):
    btree[2]=data

In [2]:
t1=binTree(2,binTree(4),binTree(8))

In [3]:
t1

[2, [4, None, None], [8, None, None]]

In [4]:
setLeft(getLeft(t1),binTree(5))

In [5]:
t1
# 这里list里面的额嵌套深度就是这棵树的高度

[2, [4, [5, None, None], None], [8, None, None]]

## code 2
原书第186页【page 186】  
用tuple构造二叉表达式树

In [11]:
def makeSum(a,b):
    return ('+',a,b)
def makeProd(a,b):
    return ('*',a,b)
def makeDiff(a,b):
    return ('-',a,b)
def makeDiv(a,b):
    return ('/',a,b)
def isBasicExp(a):
    return not isinstance(a,tuple)
def isNumber(x):
    return (isinstance(x,int) or isinstance(x,float) or isinstance(x,complex))

In [8]:
# 一个简单表达式的例子
e1=makeProd(3,makeSum(2,5))

In [9]:
e1

('*', 3, ('+', 2, 5))

In [10]:
makeSum(makeProd('a',2),makeProd('b',7))

('+', ('*', 'a', 2), ('*', 'b', 7))

In [13]:
isNumber(10)

True

In [14]:
isBasicExp(e1)

False

In [22]:
# 表达式求值
def  evalSum(a,b):
    if isNumber(a) and isNumber(b):
        return a+b
    elif isNumber(a) and a==0:
        return b
    elif isNumber(b) and b==0:
        return a
    else:
        return makeSum(a,b)
    
def  evalProd(a,b):
    if isNumber(a) and isNumber(b):
        return a*b
    elif isNumber(a):
        if a==0:
            return 0
        elif a==1:
            return b
    elif isNumber(b):
        if b==0:
            return 0
        elif b==1:
            return a
    else:
        return makeProd(a,b)    

def evalDiff(a,b):
    if isNumber(a) and isNumber(b):
        return a-b
    elif isNumber(b) and b==0:
        return a
    else:
        return makeDiff(a,b)

def evalDiv(a,b):
    if isNumber(a) and isNumber(b):
        return a/b
    elif isNumber(a) and a==0:
        return 0
    elif isNumber(b):
        if b==1:
            return a
        elif b==0:
            raise ZeroDivisionError
    return makeDiv(a,b)
    
def evalExp(e):
    if isBasicExp(e):
        return e
    else:
        op,a,b=e[0],evalExp(e[1]),evalExp(e[2])
        if op=='+':
            return evalSum(a,b)
        elif op=='-':
            return evalDiff(a,b)
        elif op=='*':
            return evalProd(a,b)
        elif op=='/':
            return evalDiv(a,b)
        else:
            raise ValueError("Unknown operator:",op)

In [23]:
e1

('*', 3, ('+', 2, 5))

In [24]:
evalExp(e1)

21

## code 3
原书第190页【page 190】  
用list实现的优先队列类

In [23]:
class PrioQueueError(ValueError):
    pass
class PrioQue:
    def __init__(self,elist=[]):
        self._elems=list(elist)
        # 定义较小的值为高优先级，放在表的末尾方便访问
        self._elems.sort(reverse=True)
    def enqueue(self,e):
        # 插入元素是这里最复杂的操作
        i = len(self._elems)-1
        while i>=0:
            # 找到合适的插入位置
            if self._elems[i]<=e:
                i-=1
            else:
                break
        self._elems.insert(i+1,e)
    def isEmpty(self):
        return len(self._elems)==0
    def peeok(self):
        if self.isEmpty():
            PrioQueueError("In top!")
        return self._elems[-1]
    def dequeue(self):
        if self.isEmpty():
            PrioQueueError("In dequeue!")
        return self._elems.pop()

In [24]:
import numpy as np
elist=np.random.randint(0,30,size=(10))
print(elist)
p1=PrioQue(elist)
for i in range(5):
    print(p1.dequeue(),end=" ")
print()
for i in range(10):
    x=np.random.randint(0,50)
    print(x,end=" ")
    p1.enqueue(x)
    print(p1.dequeue())

[18 24  2  7 23 25 15 26  0 15]
0 2 7 15 15 
22 18
44 22
3 3
31 23
10 10
28 24
39 25
6 6
13 13
34 26


## code 4
原书第193页【page 193】  
用堆实现优先队列

In [15]:
class PrioQueue:
    """
    implementation priority queues by using heaps
    """
    def __init__(self,elist=[]):
        self._elems=list(elist)
        if len(elist)>0:
            # 如果初始化列表非空则执行初始化一个堆
            self.buildHeap()
    def isEmpty(self):
        return len(self._elems)==0
    def peek(self):
        if self.isEmpty():
            raise PrioQueueError("In peek!")
        # 查看堆顶元素
        return self._elems[0]
    def enqueue(self,e):
        # 增加一个空元素位置给即将入队的元素提供位置
        self._elems.append(None)
        self.siftUp(e,len(self._elems)-1)
    def siftUp(self,e,last):
        """
        1. 向上过滤的过程，将e放在最后，每次和其父节点表示，当小于父节点时将e与父节点交换
        2. 节点i的父节点位于 (i-1)//2
        3. 节点i的左右子节点位于 2*i+1,2*i+2
        """
        elems,i,j=self._elems,last,(last-1)//2
        while i>0 and e <elems[j]:
            elems[i]=elems[j]
            i,j=j,(j-1)//2
        elems[i]=e
    def dequeue(self):
        if self.isEmpty():
            raise PrioQueueError("In dequeue!")
        elems=self._elems
        # 去除堆顶元素
        e0=elems[0]
        # 取出最后一个元素放到堆顶
        e=self._elems.pop()
        # 开始做一遍向下筛选过滤以维持堆的性质
        if len(elems)>0:
            self.siftDown(e,0,len(elems))
        # 返回原来的额堆顶元素
        return e0
    def siftDown(self,e,begin,end):
        elems,i,j=self._elems,begin,begin*2+1
        # i是父节点，j是左子节点
        while j<end:
            if j+1 < end and  elems[j+1]<elems[j]:
                j+=1
                # elems[j]不大于其兄弟节点中的数据
            if e<elems[j]:
                break
            # 此时e，elems[j],elems[j+1]三者中的最小值赋值给父节点elems[i]
            elems[i]=elems[j]
            i,j=j,2*j+1
        elems[i]=e
    def  buildHeap(self):
        end=len(self._elems)
        for i in range(end//2,-1,-1):
            self.siftDown(self._elems[i],i,end)
            # print(self._elems)

In [17]:
import numpy as np
lst=np.random.randint(0,50,size=15)
print(lst)
q2=PrioQueue(elist=lst)
print("一次构造：")
for i in range(len(q2._elems)):
    print(q2._elems[i],end=" ")
print()
q3=PrioQueue()
for i in range(len(lst)):
    q3.enqueue(lst[i])
print("逐个增加：")
for i in range(len(q3._elems)):
    print(q3._elems[i],end=" ")
print()

[14  4 41 24 23  1 39 37 43  9  3 26 44 38 18]
一次构造：
1 3 14 24 4 26 18 37 43 9 23 41 44 38 39 
逐个增加：
1 3 4 24 9 26 18 37 43 23 14 41 44 39 38 


## code 5
原书第196页【page 196】  
堆排序的实现

In [18]:
def sortHeap(elems):
    def siftDown(elems,e,begin,end):
        i,j=begin,begin*2+1
        while j<end:
            if j+1<end and elems[j+1]<elems[j]:
                j+=1
            if e<elems[j]:
                break;
            elems[i]=elems[j]
            i,j=j,2*j+1
        elems[i]=e
    
    end=len(elems)
    for i in range(end//2,-1,-1):
        siftDown(elems,elems[i],i,end)
        # 初始舰堆时间为O(nlog(n))
    for i in range(end-1,0,-1):
        e=elems[i]
        elems[i]=elems[0]
        siftDown(elems,e,0,i)

In [19]:
import numpy as np
lst=np.random.randint(0,50,size=15)
print("origianl arrangement:")
print(lst)
q3=PrioQueue(elist=lst)
print("heap struction:")
print(q3._elems)
print("after sortHeap:")
sortHeap(lst)
print(lst)

origianl arrangement:
[32  1 28 24 28 16 43 18 35 44 35 45 21 37 26]
heap struction:
[1, 18, 16, 24, 28, 21, 26, 32, 35, 44, 35, 45, 28, 37, 43]
after sortHeap:
[45 44 43 37 35 35 32 28 28 26 24 21 18 16  1]


## code 6
原书第197页【page 197】  
离散事件模拟，通用的离散框架

In [34]:
# 通用的模拟系统框架、
from random import randint
# from prioqueue import PrioQueue
# PrioQueue是code 4中用堆结构实现的优先队列类

# 导入队列的定义，用于事件排队 

# 队列空时无法访问异常
class QueueUnderFlow(ValueError):
    pass
class SQueue():
    def __init__(self,init_len=8):
        # 存储区长度
        self._len=init_len
        # 存储区（元素存储）
        self._elems=[0]*self._len
        # 队首元素下标
        self._head=0
        # 元素个数
        self._num=0
    def isEmpty(self):
        return self._num==0
    def peek(self):
        if self.isEmpty():
            raise QueueUnderFlow
        return self._elems[self._head]
    def dequeue(self):
        if self.isEmpty():
            raise QueueUnderFlow
        # 出队操作
        e=self._elems[self._head]
        # 出队一个元素之后队首后移，队列元素数减一，保持数据不变式
        self._head=(self._head+1)%self._len
        self._num-=1
        return e
    def enqueue(self,elem):
        if self._len==self._num:
            # 队列满时扩大存储区
            self.__extend()
        self._elems[(self._head+self._num)%self._len]=elem
        self._num+=1
    def __extend(self):
        old_len=self._len
        self._len*=2
        new_elems=[0]*self._len
        for i in range(old_len):
            new_elems[i]=self._elems[(self._head+i)%old_len]
        self._elems=new_elems
        self._head=0

class Simulation:
    def __init__(self,duration):
        self._eventq=PrioQueue()
        self._time=0
        self._duration=duration # 模拟器的工作时间段，即需要模拟的总时长
        
    def run(self):
        while not self._eventq.isEmpty():
            # 开始模拟所有实践，知道事件队列为空
            event=self._eventq.dequeue()
            self._time=event.time() # 事件的时间即是当前时间
            if self._time>self._duration:
                break
                # 时间用完即模拟结束
            event.run()
            # 模拟这个事件的运行，这中间可能产生新的情况
    def addEvent(self,event):
        self._eventq.enqueue(event)
    def curTime(self):
        return self._time
    
# 模拟过程中可能发生的事件类
class Event:
    def __init__(self,eventTime,host):
        self._ctime=eventTime
        self._host=host
        # 这里host是宿主系统，即事件发生的模拟系统
    def __lt__(self,otherEvent):
        return self._ctime < otherEvent._ctime
    def __lr__(self,otherEvent):
        return self._ctime <= otherEvent._ctime
    def host(self):
        return self._host
    def time(self):
        return self._ctime
    def run(self):
        # 由具体事件类定义run过程中发生的情况，即发生的各种事件
        pass

## code 7
原书第199页【page 199】  
离散时间模拟系统：海关检查站模拟系统的实现

In [171]:
class Customs:
    def __init__(self,gateNum,duration,arriveInterval,checkInterval):
        self.simulation=Simulation(duration)
        self.waitLine=SQueue()
        self.duration=duration
        self.gateNum=gateNum
        self.gates=[0]*gateNum
        self.totalWaitTime=0
        self.totalUsedTime=0
        self.carNum=0
        self.arriveInterval=arriveInterval
        self.checkInterval=checkInterval
    def waitTimeAcc(self,n):
        self.totalWaitTime+=n
    def totalTimeAcc(self,n):
        self.totalUsedTime+=n
    def carCount1(self):
        self.carNum+=1
    def addEvent(self,event):
        self.simulation.addEvent(event)
    def curTime(self):
        return self.simulation.curTime()
    def enqueue(self,car):
        self.waitLine.enqueue(car)
    def hasQueuedCar(self):
        return not self.waitLine.isEmpty()
    def nextCar(self):
        return self.waitLine.dequeue()
    def getArriveInterval(self):
        return self.arriveInterval
    def getCheckInterval(self):
        return self.checkInterval
    def findGate(self):
        for i in range(self.gateNum):
            if self.gates[i]==0:
                # 表示该通道未被使用
                self.gates[i]=1
                # print("gate {} is busy".format(i))
                return i
        # 全部通道被占用
        return None
    def freeGate(self,i):
        if self.gates[i]==1:
            self.gates[i]=0
            # print("gate {} free".format(i))
        else:
            raise ValueError("Clear gate {} error!".format(i))
    # 实施模拟
    def simulate(self):
        Arrive(0,self)
        # initially generate one car
        self.simulation.run()
        self.statistics()
    # 输出统计数据
    def statistics(self):
        print("Simulation {} minutes, for {} gates...".format(self.duration,self.gateNum))
        print("{} cars pass the customs".format(self.carNum))
        print("Average waiting time:{}".format(self.totalWaitTime/self.carNum))
        print("Average passing time:{}".format(self.totalUsedTime/self.carNum))
        count=0
        while not self.waitLine.isEmpty():
            self.waitLine.dequeue()
            count+=1
        print("{} cars are in waiting line".format(count))
# 汽车类
class Car:
    def __init__(self,arriveTime):
        self.time=arriveTime
    def arriveTime(self):
        return self.time
# 输出事件发生过程中的的日志条目
def eventLog(time,name):
    print("Event: {} happens at {}.".format(name,time))
# 骑车到达与检查完毕离开，事件event类的派生类
class Arrive(Event):
    def __init__(self,arriveTime,customs):
        Event.__init__(self,arriveTime,host=customs)
        customs.addEvent(self)
    
    def run(self):
        time,customs=self.time(),self.host()
        eventLog(time,"car arrive")
        # 生成下一个arrive事件
        Arrive(time+randint(*customs.arriveInterval),customs)
        # 以下是本次到达车辆的行为
        car=Car(time)
        if customs.hasQueuedCar():
            # 如果前面有车辆排队就跟在后面
            customs.enqueue(car)
            return True
        # 否则就去查找是否有检查口空闲
        i=customs.findGate()
        if i is not None:
            # 有空闲的检查口则检查通过
            eventLog(time,"car chech")
            Leave(time+randint(*customs.checkInterval),i,car,customs)
        else:
            # 没有检查口空闲则开始排队
            customs.enqueue(car)
class Leave(Event):
    def __init__(self,leaveTime,gate,car,customs):
        Event.__init__(self,leaveTime,customs)
        self.car=car
        self.gate=gate      
        customs.addEvent(self)
    
    def run(self):
        time,customs=self.time(),self.host()
        eventLog(time,"car leave")
        customs.freeGate(self.gate)
        customs.carCount1()
        customs.totalTimeAcc(time-self.car.arriveTime())
        if customs.hasQueuedCar():
            car=customs.nextCar()
            i=customs.findGate()
            eventLog(time,"car check")
            customs.waitTimeAcc(time-car.arriveTime())
            Leave(time+randint(*customs.checkInterval),self.gate,car,customs)

In [172]:
# 实际的模拟
carArriveInterval=(1,2)
carCheckInterval=(3,5)
cus=Customs(3,480,carArriveInterval,carCheckInterval)
cus.simulate()

Event: car arrive happens at 0.
Event: car chech happens at 0.
Event: car arrive happens at 2.
Event: car chech happens at 2.
Event: car arrive happens at 4.
Event: car chech happens at 4.
Event: car leave happens at 5.
Event: car arrive happens at 6.
Event: car chech happens at 6.
Event: car leave happens at 7.
Event: car leave happens at 8.
Event: car arrive happens at 8.
Event: car chech happens at 8.
Event: car arrive happens at 10.
Event: car chech happens at 10.
Event: car leave happens at 11.
Event: car arrive happens at 11.
Event: car chech happens at 11.
Event: car leave happens at 12.
Event: car arrive happens at 12.
Event: car chech happens at 12.
Event: car leave happens at 13.
Event: car arrive happens at 14.
Event: car chech happens at 14.
Event: car leave happens at 15.
Event: car arrive happens at 15.
Event: car chech happens at 15.
Event: car leave happens at 17.
Event: car arrive happens at 17.
Event: car chech happens at 17.
Event: car leave happens at 18.
Event: car

## code 8
原书第230页【page 203】  
二叉树节点类的实现

In [1]:
class BinTNode:
    def __init__(self,data,left=None,right=None):
        self.data=data
        self.left=left
        self.right=right

In [2]:
# 构造一棵包含三个节点的二叉树
a=BinTNode(1,BinTNode(2),BinTNode(3))

In [6]:
# 验证二叉树链接实现的递归性的两个函数

# 1. 统计二叉树节点个数
def countBinTNodes(t):
    if t is None:
        return 0
    else:
        return 1+ countBinTNodes(t.left)+countBinTNodes(t.right)
    
# 2. 求二叉树中所有节点存储的数字之和
def sumBinTNodes(t):
    if t is None:
        return 0
    else:
        return t.data+sumBinTNodes(t.left)+sumBinTNodes(t.right)

In [7]:
print("number of nodes:{}".format(countBinTNodes(a)))
print("sum of node data:{}".format(sumBinTNodes(a)))

number of nodes:3
sum of node data:6


## code 9
原书第204页【page 204】  
二叉树的递归遍历实现深度优先访问

In [26]:
# 二叉树的深度优先遍历，递归实现

# 1. 先根序遍历
def preorder(t):
    if t is None:
        return
    assert(isinstance(t,BinTNode))
    print(t.data,end=" ")
    preorder(t.left)
    preorder(t.right)
# 2. 中根序遍历
def midorder(t):
    if t is None:
        return
    assert(isinstance(t,BinTNode))
    midorder(t.left)
    print(t.data,end=" ")
    midorder(t.right)
# 3. 后根序遍历
def postorder(t):
    if t is None:
        return
    assert(isinstance(t,BinTNode))
    postorder(t.left)
    postorder(t.right)
    print(t.data,end=" ")

In [27]:
b=BinTNode(1,BinTNode(2,BinTNode(4),BinTNode(5)),BinTNode(3,BinTNode(6,BinTNode(8),BinTNode(9)),BinTNode(7)))
print("preOrder:")
preorder(b)
print()
print("midOrder:")
midorder(b)
print()
print("postOrder")
postorder(b)
print()

preOrder:
1 2 4 5 3 6 8 9 7 
midOrder:
4 2 5 1 8 6 9 3 7 
postOrder
4 5 2 8 9 6 7 3 1 


## code 10
原书第204页【page 204】  
队列实现的二叉树宽度优先搜索

In [43]:
def dfsBinTree(t):
    if t is None:
        return
    assert(isinstance(t,BinTNode))
    sq=SQueue()
    sq.enqueue(t)
    while not sq.isEmpty():
        e=sq.dequeue()
        print(e.data,end=" ")
        if e.left is not None:
            sq.enqueue(e.left)
        if e.right is not None:
            sq.enqueue(e.right)

In [44]:
b=BinTNode(1,BinTNode(2,BinTNode(4),BinTNode(5)),BinTNode(3,BinTNode(6,BinTNode(8),BinTNode(9)),BinTNode(7)))
dfsBinTree(b)

1 2 3 4 5 6 7 8 9 

## code 11
原书第。。。页【page 18。。。4】  
用list实现二叉树的一组基本函数

In [45]:
(3+99)*33 / 2 + (5+95)*19 /2 -(15+90)*3

2318.0

## code 12
原书第。。。页【page 18。。。4】  
用list实现二叉树的一组基本函数

## code 13
原书第。。。页【page 18。。。4】  
用list实现二叉树的一组基本函数